---

- hosts: server
  become: true
  tasks:
    - name : get hostname
      debug:
        msg: "{{hostvars[item]['ansible_eth1']['ipv4']['address'] }}\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
      with_items:
        - "{{groups['server']}}"

    - name: Entry in etc host
      lineinfile:
        dest: "/etc/hosts"
        line: "{{hostvars[item]['ansible_eth1']['ipv4']['address'] }}\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
        backup: true
        state: present
      when: ansible_host != "{{item}}"
      with_items:
        - "{{ groups['server'] }}"

